### ISSUE TITLE
Do not mix lines when exporting txt

### ISSUE THREAD

**Issue by zabak** [DCGM/pero-ocr#16]
When exporting txt (at least txt), export the lines in the order they appear on page or in column to column order. Currently, they are sometimes ordered rather strangely. See https://pero-ocr.fit.vutbr.cz/ocr/show_results/2269d1ae-d61c-4129-9c7c-3c78bc81cd8b

**Comment by michal-hradis** [comment]
page_parser now supports paragprah ordering. The implemented method is not perfect, but it often works. The web application now supports manual re-ordering of paragraphs.
