### ISSUE TITLE
where can we find the pretrained models?

### ISSUE THREAD

**Issue by jwijffels** [DCGM/pero-ocr#19]
are there checkpoints of models which can be downloaded available somewhere?

**Comment by michal-hradis** [comment]
We have released layout/textline model and OCR  model for european printed documents. If you are interested in other models, let me know. The link is now in README.md:

General layout analysis (printed and handwritten) with european printed OCR specialized to czech newspapers can be downloaded here (https://www.fit.vut.cz/~ihradis/pero/pero_eu_cz_print_newspapers_2020-07-28.tar.gz). These models are compatible with the develop branch.

**Comment by jwijffels** [comment]
yes, I'm testing out a bit of handwritten text recognition models - would be interested to get that model as well, not only layout

**Comment by michal-hradis** [comment]
You can try a handwriting recognition model in our web application at pero-ocr.fit.vutbr.cz. The model is able to recognize some older european scripts and it is specialized for Czech. If your interest is deeper, feel free to contact me via my university email.

**Comment by jwijffels** [comment]
I've tried it already at the web application, set up the web application as well locally and noticed the models are not there, hence my question here. My interest is in training a handwritten text recognition model on 18th-19th century Dutch texts.
