### ISSUE TITLE
Website typo Layout Analysis

### ISSUE THREAD

**Issue by infelane** [DCGM/pero-ocr#21]
I suppose website related issues can also be mentioned here.

I noticed a typo for selecting the layout analysis.
Shouldn't ***Select baseline detector*** be ***Select layout detector***?

---
![Capture](https://user-images.githubusercontent.com/11060384/90618040-b9558d80-e20f-11ea-8899-37f2a5faa966.PNG)

**Comment by michal-hradis** [comment]
Thanks, it is fixed. Will be live in a day.
