### ISSUE TITLE
Where does model for region detector place?

### ISSUE THREAD

**Issue by lynx97** [DCGM/pero-ocr#25]
I run script with layout detection.
In the class `EngineRegionDetector`
It has error 
`Cannot interpret feed_dict key as Tensor: The name 'inference_input:0' refers to a Tensor which does not exist. The operation, 'inference_input', does not exist in the graph.` in line 75

**Comment by OldaKodym** [comment]
Hi,

please try checking out the develop branch of the repository and running layout detection with the newest models and config. It can be downloaded from here: https://www.fit.vut.cz/~ihradis/pero/pero_eu_cz_print_newspapers_2020-10-09.tar.gz

Let us know if the problem persists.
