### ISSUE TITLE
PERO generates 0kB ALTO files

### ISSUE THREAD

**Issue by erikamirova** [DCGM/pero-ocr#49]
checking for zero ALTO file size would probably help

![image](https://user-images.githubusercontent.com/37616300/222073035-7b2a9752-b599-4cc7-aef8-cffab85fe34f.png)

**Comment by erikamirova** [comment]
@michal-hradis Dobrý den, mohl byste na to mrknout, prosím? Děkujeme :)

**Comment by zabak** [comment]
@erikamirova prosím připiš sem od kdy sse to začalo dít. A případně kdyby mohl Lukáš doplnit ID nějakých jobů kde ten problém nastal.

**Comment by erikamirova** [comment]
Děje se to od 27. 1. S Lukášem se domluvím a ty ID když tak doplníme.

**Comment by michal-hradis** [comment]
@erikamirova Prosím o další informace. Předpokládám, že problém se netýká přímo balíčku pero-ocr, ale [API](https://github.com/DCGM/pero-ocr-api). Z toho budu vycházet. Potřebuju aspoň ID úlohy. V jaké stavu skočnilo zpracování daných stránek? Bylo to "PROCESSED"? Doopravdy API poslalo soubory s nulovou velikostí? U nás žádné ALTO s nulovou velikostí nevidím.

**Comment by michal-hradis** [comment]
Od 27. nejsou ani žádné vaše stránky, které by selhaly. Výpis počtů stránek podle stavů pro vaše úlohy jsou:

**Comment by Vacii** [comment]
Dobrý den,
 zkontroloval jsem dokumenty, které kolegyni dělaly problém. Po dodatečném stažení ALTO souborů jsem zjistil, že jsou od Vás dodávány správně. Problém nejpravděpodobněji nastal při stažení souborů. Implementoval jsem tedy do našeho skriptu test na nulové XML soubory, který je případně stáhne znovu.

Když už ale řešíme XML soubory; všiml jsem si, že u nich chybí takové ty klasické XML hlavičky "<?xml version='1.0' encoding='utf-8'?>". Je k tomu prosím nějaký důvod, případně šlo by je tam z vaší strany přidat?
