### ISSUE TITLE
Transcription

### ISSUE THREAD

**Issue by halaneji** [DCGM/pero-ocr#62]
For old latin transcription, which model should i select to generate the OCR of the below image please?
![image](https://github.com/DCGM/pero-ocr/assets/18636817/5bc52466-f0a4-4128-a519-a5b0c795a410)

**Comment by ikiss-fit** [comment]
Hi, if you are trying to process this document with the pero-ocr web application (pero-ocr.fit.vutbr.cz), you can use the **Complex printed and handwritten layout** model. For the baseline detector model, select **Universal**. For the OCR model you can definitely try **Universal Transformer**, but it will probably be quite slow. Otherwise, you can try **Czech Fraktur Printed** or **German Fraktur Printed** on this document, but without the language model (leave NONE selected). Of course, you can try different settings to see what works best for you.

If your question was not about the pero-ocr web application, then I would need more information to assist you.

**Comment by halaneji** [comment]
Thank you so much for your reply,
My question about the model when i run the test in my local repository, because I use the pero-ocr model that is shared, this is the  configuration that i use it :
import os
import configparser
import cv2
import numpy as np
from pero_ocr.core.layout import PageLayout
from pero_ocr.document_ocr.page_parser import PageParser

# Read config file.
config_path = "./config.ini"
config = configparser.ConfigParser()
config.read(config_path)

# Init the OCR pipeline. 
# You have to specify config_path to be able to use relative paths
# inside the config file.
page_parser = PageParser(config, config_path=os.path.dirname(config_path))

# Input and output directories
input_dir = "input/"
output_dir = "output/"

# Create output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Process each image in the input directory
for filename in os.listdir(input_dir):
    if filename.endswith(".tiff") or filename.endswith(".png"):
        input_image_path = os.path.join(input_dir, filename)
        
        # Read the document page image.
        image = cv2.imread(input_image_path, 1)
        
        # Init empty page content. 
        # This object will be updated by the ocr pipeline. id can be any string and it is used to identify the page.
        page_layout = PageLayout(id=input_image_path, page_size=(image.shape[0], image.shape[1]))
        
        # Process the image by the OCR pipeline
        page_layout = page_parser.process_page(image, page_layout)
        
        # Save results as Page XML.
        output_page_xml = os.path.join(output_dir, f"{os.path.splitext(filename)[0]}.xml")
        page_layout.to_pagexml(output_page_xml)
        
        # Save results as ALTO XML.
        output_alto_xml = os.path.join(output_dir, f"{os.path.splitext(filename)[0]}_ALTO.xml")
        page_layout.to_altoxml(output_alto_xml)
        

With this script how can i select the Universal Transformer model please ??

**Comment by ikiss-fit** [comment]
The Universal Transformer model is not publicly available. It is available only in the pero-ocr web application (pero-ocr.fit.vutbr.cz).

**Comment by halaneji** [comment]
is it possible to share it with me please??

**Comment by ikiss-fit** [comment]
I'm sorry, but we will not share the model with you. If you want to process documents with our latest models, you can use the free web application pero-ocr (pero-ocr.fit.vutbr.cz). In case you need to process a really large amount of documents, we could discuss it and maybe the processing could be done via API, but that would probably be for a fee.

**Comment by halaneji** [comment]
Yes I will process a large amount of documents, for this reason I should have a solution for that.
Thanks for your response!

**Comment by ikiss-fit** [comment]
OK, I would suggest continuing the conversation via email. Could you send me an email to ikiss@fit.vutbr.cz so we can discuss this further?

**Comment by halaneji** [comment]
Yes for sure, thank you so much.
