### ISSUE TITLE
Couldn't find pero_ocr.document_ocr.layout

### ISSUE THREAD

**Issue by DirkWuerdemann** [DCGM/pero-ocr#64]
I have copied the python script from the pypi.org page into a python script and I get the following Error:

  File "X:\Data\python\OCR\pero-ocr\test-ocr.py", line 5, in <module>
    from pero_ocr.document_ocr.layout import PageLayout
ModuleNotFoundError: No module named 'pero_ocr.document_ocr.layout'

I am running it under Windows 11.
Any solution?

kind regards
Dirk

**Comment by ikiss-fit** [comment]
Please, use the import from the github README:

```python
from pero_ocr.core.layout import PageLayout
```

We will update this information at pypi as soon as possible.

**Comment by DirkWuerdemann** [comment]
Thx, this works. But now I have an Error with the config file.
Where can I find one? Or how can I create one? Syntax ?

Traceback (most recent call last):
  File "X:\Data\python\OCR\pero-ocr\test-ocr.py", line 16, in <module>
    page_parser = PageParser(config, config_path=os.path.dirname(config_path))
  File "C:\Users\DirkWuer\AppData\Local\Programs\Python\Python310\lib\site-packages\pero_ocr\document_ocr\page_parser.py", line 459, in __init__
    self.run_layout_parser = config['PAGE_PARSER'].getboolean('RUN_LAYOUT_PARSER', fallback=False)
  File "C:\Users\DirkWuer\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'PAGE_PARSER'

Process finished with exit code 1
kr
Dirk

**Comment by DirkWuerdemann** [comment]
Many thx again. 
now I tried to import

from pero_ocr.document_ocr import DocumentOCR

and also I here I get a message that DocumentOCR was not found. What do I need to change?
kr
Dirk

**Comment by ikiss-fit** [comment]
There's no such thing as `DocumentOCR`. From `pero_ocr/document_ocr/page_parser.py` you can import `PageParser` which implements the processing pipeline. See the [intergration of pero-ocr](https://github.com/DCGM/pero-ocr?tab=readme-ov-file#integration-of-the-pero-ocr-python-module) section in README.
